openapi: 3.0.0
info:
  version: "1.0.0"
  title: University Life Manager API
  description: >-
    This is an OpenAPI specification for the University Life Manager backend. Request/response objects can be specified
    in components. Endpoints can be specified in paths.
servers:
  # Base path for endpoints
  - url: /api/v1
security:
  # By default, all endpoints require a bearer token
  - bearerAuth: []
paths:
  /signup:
    post:
      summary: Creates a new user (signup)
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignupInfo'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
        '400':
          $ref: '#/components/responses/BadRequest'
  /user:
    get:
      summary: Get user's information
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/UserInfo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/AuthorizationError'
        '404':
          $ref: '#/components/responses/NotFoundError'
# Do not use this endpoint anymore
#    put:
#      summary: Update user's information
#      requestBody:
#        content:
#          application/json:
#            schema:
#              $ref: '#/components/schemas/UserInfo'
#      responses:
#        '200':
#          description: OK
#          content:
#            application/json:
#              schema:
#                $ref: '#/components/schemas/UserInfo'
#        '400':
#          $ref: '#/components/responses/BadRequest'
#        '401':
#          $ref: '#/components/responses/AuthorizationError'
#        '404':
#          $ref: '#/components/responses/NotFoundError'
  /login:
    post:
      summary: Exchange username and password for access token
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserCredentials'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccessToken'
        '401':
          $ref: '#/components/responses/AuthorizationError'
  /schedule:
    post:
      summary: Request generation of a new schedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleInfo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleInfo'
        '401':
          $ref: '#/components/responses/AuthorizationError'
    put:
      summary: Update the current schedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ScheduleInfo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ScheduleInfo'
        '401':
          $ref: '#/components/responses/AuthorizationError'
  /course:
    post:
      summary: Create a new course for the user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInfo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseInfo'
        '401':
          $ref: '#/components/responses/AuthorizationError'
  /course/{courseId}:
    put:
      summary: Update a course for the user
      parameters:
        - name: courseId
          in: path
          description: Course ID
          required: true
          schema:
            type: string
            pattern: "[a-z0-9]+"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CourseInfo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CourseInfo'
        '401':
          $ref: '#/components/responses/AuthorizationError'
  /course/{courseId}/deliverable:
    post:
      summary: Create a new deliverable for the user's course
      parameters:
        - name: courseId
          in: path
          description: Course ID
          required: true
          schema:
            type: string
            pattern: "[a-z0-9]+"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliverableInfo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliverableInfo'
        '401':
          $ref: '#/components/responses/AuthorizationError'
  /course/{courseId}/deliverable/{deliverableId}:
    put:
      summary: Update a deliverable for the user's course
      parameters:
        - name: courseId
          in: path
          description: Course ID
          required: true
          schema:
            type: string
            pattern: "[a-z0-9]+"
        - name: deliverableId
          in: path
          description: Deliverable ID (auto-generated on deliverable creation)
          required: true
          schema:
            type: string
            pattern: "[a-z0-9]+"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliverableInfo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliverableInfo'
        '401':
          $ref: '#/components/responses/AuthorizationError'
  /course/{courseId}/timespent:
    post:
      summary: Create a new time spent for the user's course
      parameters:
        - name: courseId
          in: path
          description: Course ID
          required: true
          schema:
            type: string
            pattern: "[a-z0-9]+"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TimeSpentInfo'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TimeSpentInfo'
        '401':
          $ref: '#/components/responses/AuthorizationError'
components:
  responses:
    AuthorizationError:
      description: Credentials are missing or invalid
    BadRequest:
      description: A malformed request could not be processed, e.g. a field must be unique or non-empty but was not
    NotFoundError:
      description: Entity could not be found
  # Request and response objects, see https://app.swaggerhub.com/apis/j84guo/iot-api/1.0.0 for more examples
  schemas:
    CourseInfo:
      type: object
      properties:
        course_id:
          type: string
          minLength: 1
          pattern: "[a-z0-9]+"
        course_name:
          type: string
          minLength: 1
        expected_difficulty:
          type: integer
          format: int32
          minimum: 1
          maximum: 5
        desired_grade:
          type: integer
          format: int32
          minimum: 0
          maximum: 100     
        deliverables:
          type: object
          additionalProperties:
           $ref: '#/components/schemas/DeliverableInfo'
        time_spent:
          type: array
          items:
            $ref: '#/components/schemas/TimeSpentInfo'
      required:
        - 'course_id'
        - 'course_name'
        - 'expected_difficulty'   
        - 'desired_grade'
    DeliverableInfo:
      type: object
      properties:
        deliverable_id:
          type: string
          minLength: 1
          pattern: "[a-z0-9]+"
        deliverable_name:
          type: string
          minLength: 1
        grade:
          type: number
          minimum: 0
          maximum: 100
        weight:
          type: number
          minimum: 0
          maximum: 100     
        due_at:
          type: string
          format: date-time
        completed:
          type: boolean
      required:
        - 'deliverable_name'
        - 'weight'   
        - 'due_at'
        - 'completed'
    TimeSpentInfo:
      type: object
      properties:
        notes:
          type: string
          minLength: 1   
        started_at:
          type: string
          format: date-time
        ended_at:
          type: string
          format: date-time
      required:
        - 'notes'
        - 'started_at'
        - 'ended_at'   
    UserInfo:
      type: object
      properties:
        current_schedule:
          $ref: '#/components/schemas/CourseInfo'
        time_recorded:
          additionalProperties:
            type: number
          type: object
        username:
          type: string
          minLength: 1
        email:
          type: string
          minLength: 1
        joined_at:
          format: date-time
          type: string
        courses:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/CourseInfo'
      required:
          - 'username'
          - 'email'
    UserCredentials:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - 'username'
        - 'password'
    AccessToken:
      type: object
      properties:
        access_token:
          type: string
      required:
        - 'access_token'
    SignupInfo:
      type: object
      properties:
        email:
          type: string
          minLength: 1
        username:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
        - 'email'
        - 'username'
        - 'password'
    ScheduleInfo:
      type: object
      properties:
        starts_at:
          format: date
          type: string
        ends_at:
          format: date
          type: string
        max_study_hours:
          type: integer
          format: int32
          minimum: 1
        time_allocations:
          type: object
          additionalProperties:
            type: number
      required:
        - 'starts_at'
        - 'ends_at'
        - 'max_study_hours'
  securitySchemes:
    # Example configuration for bearer token authentication
    bearerAuth:
      type: http
      scheme: bearer

